### ISSUE TITLE
patchelf tool

### ISSUE THREAD

**Issue by magicse** [clandmeter/alpine-docker-gitlab#13]
Please update patchelf for Alpine 3.16 due issue for armv7 cpus.
https://github.com/NixOS/patchelf/issues/474
https://github.com/brenoguim/patchelf/tree/breno.474

**Comment by Ikke** [comment]
@magicse Is this in any way related to Gitlab? If not, I'd recommend you open an issue on https://gitlab.alpinelinux.org/alpine/aports/-/issues/
