### ISSUE TITLE
GitLab on Docker without Chef?

### ISSUE THREAD

**Issue by dm17** [clandmeter/alpine-docker-gitlab#7]
I see the official images still use Chef in Docker... Any thoughts on being able to achieve GitLab in Docker without Chef? Or too much work?

**Comment by Ikke** [comment]
This image does not use chef at all. It has a [setup](https://github.com/alpinelinux/alpine-docker-gitlab/blob/master/gitlab/overlay/usr/local/bin/setup.sh) script that does all the installation. It's available as [alpine/alpine-docker-gitlab](https://hub.docker.com/r/alpinelinux/alpine-docker-gitlab).

**Comment by dm17** [comment]
Great. I wish the official GitLab setup used alpine!

**Comment by dm17** [comment]
@Ikke have you tried alpine/alpine-docker-gitlab? Seems it only has 400 pulls...
