### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by yelena870513** [clandmeter/alpine-docker-gitlab#9]
I got error building container
```
 => ERROR [3/3] RUN  setup.sh                                                                                      0.6s
------
 > [3/3] RUN  setup.sh:
#7 0.617 /bin/sh: setup.sh: not found
------
executor failed running [/bin/sh -c setup.sh]: exit code: 127
ERROR: Service 'gitlab' failed to build : Build failed

D:\gitlab\alpine-docker-gitlab>

```

**Comment by Ikke** [comment]
Hello @yelena870513 

Which branch are you building exactly? Make sure you use something recent, like 14.10-stable. 

The development of this project happens on https://github.com/alpinelinux/alpine-docker-gitlab/issues/9, and this is just a mirror. There we also run the pipelines to build the images which are pushed to docker hub.

**Comment by yelena870513** [comment]
Thank @Ikke I am building master branch, I fixed the build, now the container is not able to run
```
gitlab_ci   | psql: fe_sendauth: no password supplied
gitlab_ci   | Password for user postgres:
gitlab_ci   | psql: fe_sendauth: no password supplied
```

I am using .env variables for each container. But it seems not readable

**Comment by yelena870513** [comment]
> Hello @yelena870513
> 
> Which branch are you building exactly? Make sure you use something recent, like 14.10-stable.
> 
> The development of this project happens on #9, and this is just a mirror. There we also run the pipelines to build the images which are pushed to docker hub.

Using this version of mirrored.

**Comment by Ikke** [comment]
We don't really use the master branch in this repo anymore, and it's not updated. Checkout `14.10-stable` to get the latest version of gitlab that we have (I didn't have time yet to build 15.0). 

Also make sure you follow the [setup](https://github.com/alpinelinux/alpine-docker-gitlab#setup) instructions for setting the environment variables.
